{% set name = "gcloud-aio-storage" %}
{% set version = "9.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_storage-{{ version }}.tar.gz
  sha256: a9a97e4cc87482b6737886b8bd8ae01475c6fc357a4fdb1f2464391b7b5d5d75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - aiofiles >=0.6.0,<25.0.0
    - gcloud-aio-auth >=5.3.0,<6.0.0
    - pyasn1-modules >=0.2.1,<0.4.2
    - rsa >=3.1.4,<5.0.0

test:
  imports:
    - gcloud.aio.storage
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Storage
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
